### ISSUE TITLE
How to enable default share of docker-machine (/c/Users)

### ISSUE THREAD

**Issue by rogeriopradoj** [portapps/docker-toolbox-portable#1]
Hi, do you think it would be a good option having instructions on how to enable, besides [data\shared](https://github.com/portapps/portapps.github.io/blob/dev/src/_includes/app/infos/docker-toolbox.md#mount-a-volume), the original shared folder of docker-toolbox on windows (c/Users -> c:\Users, auto-mount, full)?

I think it should be a good addition to the info page for new comers as me.

---

Just to point, I tried this way, and it seems to work (in docker toolbox terminal):

- verify current shared folders

```shell
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" showvminfo default

# Shared folders:
#
#Name: 'shared', Host path: '\\?\C:\Users\MY_NAME\PortableApps\docker-toolbox-portable\data\shared' #(machine mapping), writable
```

- add "default share" "c/Users" pointing to "c:\Users"

```shell
# stop machine
docker-machine stop

# actual command
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" sharedfolder add default --name "c/Users" --hostpath "\\\?\c:\Users" --automount

# restart machine
docker-machine start
```

- verify shared folders after command

```shell
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" showvminfo default

# Shared folders:
#
#Name: 'shared', Host path: '\\?\C:\Users\MY_NAME\PortableApps\docker-toolbox-portable\data\shared' (machine mapping), writable
#Name: 'c/Users', Host path: '\\?\c:\Users' (machine mapping), writable
```

**Comment by crazy-max** [comment]
Hi @rogeriopradoj, as it's a portable app this feature will not be included but you can easily fork this repository, [edit this line](https://github.com/portapps/docker-toolbox-portable/blob/master/main.go#L87) to include your custom path and make your own release. But I have to write the documentation to build a portapp project. I keep you in touch!
