### ISSUE TITLE
Start of docker-toolbox-portable.exe interrupted

### ISSUE THREAD

**Issue by m5m5k** [portapps/docker-toolbox-portable#12]
#### Steps to reproduce this issue

1. Run docker-toolbox-portable.exe

#### Expected behaviour

> A Docker-Toolbox-GUI

#### Actual behaviour

> A commandline-window opens with following message: "Looks like something went wrong in step ´Looking for VBoxManage.exe´... Press any key to continue..."

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 19.03.1-6 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** : Version 1909 (Build 18.363.476)
[docker-toolbox-portable.log](https://github.com/portapps/docker-toolbox-portable/files/3931027/docker-toolbox-portable.log)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@m5m5k As stipulated on [docker-toolbox portable page](https://portapps.io/app/docker-toolbox-portable/):

> VirtualBox needs to be installed !
