### ISSUE TITLE
Win 32 version not working

### ISSUE THREAD

**Issue by geoman2** [portapps/docker-toolbox-portable#2]
Hi

I have downloaded the 32 bit version and tried to run the docker-compose.exe file and I get a message
"This version of docker-compose.exe is not compatible with the version of the Windows you're running. Check your computer's system information"

What is wrong with it?

**Comment by crazy-max** [comment]
Hi @geoman2, you're right, there is no more win32 version available for Docker Toolbox anymore. I will update the latest release.

**Comment by geoman2** [comment]
Hi
I managed to download the 32bit version using the pip tool from python and it works.
Would be nice from you to give it a try and test it to make sure it is working and add it to the docker toolbox package and relist it again.
