### ISSUE TITLE
Error: Looks like something went wrong in step ´Looking for VBoxManage.exe´... Press any key to continue...

### ISSUE THREAD

**Issue by k-allika** [portapps/docker-toolbox-portable#23]
### Behaviour
When I double click docker-toolbox-portable.exe, it opens a command prmpt and displays the following message in it.
`Looks like something went wrong in step ´Looking for VBoxManage.exe´... Press any key to continue...`

Then I press some key and the window closes. So the program does not open.

#### Steps to reproduce this issue

1. Tried it multiples times.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour
It's supposed to open a docker prompt.

> Tell me what happens instead
The command prompt closed and the program closed.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
docker-toolbox-portable-win64-19.03.1-6.7z

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro 64-bit

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

![r0053100](https://user-images.githubusercontent.com/31384629/89032296-ff76aa00-d351-11ea-9540-bb36686ac145.png)

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

[docker-toolbox-portable.log](https://github.com/portapps/docker-toolbox-portable/files/5006852/docker-toolbox-portable.log)

### Screenshots
> If applicable, add screenshots to help explain your problem.
![r0053110](https://user-images.githubusercontent.com/31384629/89032500-71e78a00-d352-11ea-865e-8c0d07f0b5f8.png)

**Comment by crazy-max** [comment]
@k-allika Looks like VirtualBox is not installed on your computer. See #12
