### ISSUE TITLE
Not working at win10

### ISSUE THREAD

**Issue by success-0627** [portapps/docker-toolbox-portable#31]
When execute `docker-toolbox-portable.exe` first time, always failed with 
```
Docker: Host does not exist: “default”
```

**Reason:**
https://github.com/portapps/docker-toolbox-portable/blob/68b41a5f312760a8cfb3b7580ebf692806d47dd4/res/start.sh#L45
this line seems like to check default vm exists / storage path exists.
But second condition does not work.

After I change this as below, I can get work.
```bash
if [ $VM_EXISTS_CODE -eq 1 ]; then
```

Also, I always get error 
```
bad argements: [
```

Would you please take a look and fix ?
Thank you.

**Comment by crazy-max** [comment]
@zl910627 See #22 and also https://portapps.io/news/2020-11-04-docker-toolbox-portable-abandoned/
