### ISSUE TITLE
Win32bit docker-compose seems to work

### ISSUE THREAD

**Issue by geoman2** [portapps/docker-toolbox-portable#4]
Hi

I have downloaded the 32 bit version docker-compose python package using pip and it seems to run fine.

Can someone try to see if it's really working and repackage the 32bit of docker toolbox and make it public?

**Comment by crazy-max** [comment]
Hi @geoman2, feel free to open a PR to bring back 32-bit package or maybe you could ask on the [official repository](https://github.com/docker/toolbox/issues).

**Comment by caspertone2003** [comment]
@crazy-max 
Done
https://github.com/docker/toolbox/issues/839
