### ISSUE TITLE
Issue inside VirtualBox guest?

### ISSUE THREAD

**Issue by caspertone2003** [portapps/docker-toolbox-portable#5]
@crazy-max 

Hi!

Sorry to disturb you again...

Today I started to play with docker. So, I tried to use crazymax/dokuwiki
under Docker-Toolbox-portable. I run all inside a Virtual Box guest, W10@X64Pro

Version of DTP:
"id": "docker-toolbox-portable",
  "guid": "{48C915A3-3093-45D4-B92B-E9D1EE94AFD3}",
  "name": "Docker Toolbox Portable",
  "version": "18.09.3",
  "release": "5",
  "date": "2019/03/17 21:51:56",
  "publisher": "CrazyMax",
  "url": "https://github.com/portapps/docker-toolbox-portable",
  "portapps_version": "1.20.3"

Issues the following message, then exits

**<img width="695" alt="Captura" src="https://user-images.githubusercontent.com/4682903/58340074-46facf80-7e4b-11e9-86ec-166c183cb8bb.PNG">**

Log:

Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:76 > --------
Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:77 > Starting Docker Toolbox...
Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:78 > Root path: C:\DCK\Portables\HSis\Compo\DockerToolbox
Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:82 > Loading main configuration...
Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:87 > Decoding app configuration...
Fri, 24 May 2019 17:37:00 CEST INF C:/portapps_opt/gopath/pkg/mod/github.com/portapps/portapps@v1.20.3/portapps.go:93 > Configuration:
common:
  args: []
  env: {}
app:
  machine:
    name: default
    host_cidr: 192.168.99.1/24
    cpu: 1
    ram: 1024
    disk: 20000
    shared_name: shared
    on_exit_stop: false
    on_exit_remove: false

Fri, 24 May 2019 17:37:00 CEST INF C:/Users/travis/build/portapps/docker-toolbox-portable/main.go:73 > Initializing git...
Fri, 24 May 2019 17:37:02 CEST INF C:/Users/travis/build/portapps/docker-toolbox-portable/main.go:79 > Setting machine environment...
Fri, 24 May 2019 17:37:02 CEST INF C:/Users/travis/build/portapps/docker-toolbox-portable/main.go:89 > Adding app to PATH...
Fri, 24 May 2019 17:37:02 CEST INF C:/Users/travis/build/portapps/docker-toolbox-portable/main.go:92 > Starting up the shell... 
Fri, 24 May 2019 17:37:13 CEST INF C:/Users/travis/build/portapps/docker-toolbox-portable/main.go:103 > Exiting...

Is it not possible to run DTP inside a virtualbox guest?

I found in this page https://docs.docker.com/machine/get-started/ 

"IF YOU ARE USING DOCKER DESKTOP FOR WINDOWS
Docker Desktop for Windows uses Microsoft Hyper-V for virtualization, and Hyper-V is not compatible with Oracle VirtualBox. Therefore, you cannot run the two solutions simultaneously. But you can still use docker-machine to create more local VMs by using the Microsoft Hyper-V driver."

But, later gives contradictory information....

Thanks in advance,
CT

**Comment by crazy-max** [comment]
Hi @caspertone2003,

* Docker Desktop = HyperV
* Docker Toolbox = VirtualBox

From the message it seems that you did not install VirtualBox. You should also know that VirtaulBox does not work if HyperV is enabled on Windows.

**Comment by caspertone2003** [comment]
@crazy-max 
Thanks.
No, I have not virtualbox installed in the virtualbox guest... I was expecting to simply run Docker Toolbox portable and not needing anything else... Portable concept is not fully defined, usually implies running without other external dependencies... but not always. Perhaps I missed this behaviour in the documentation.... might be obvious by I am learning about dockers... if it is not there, perhaps a line of "pre-requisites" in docker toobox portable would be nice...
I will install virtualbox inside my virtualbox guest - I know that nested virtualization is unclear ... seems that it is ok to have 32 guests inside 64 guest...
Will report back...
CT

**Comment by crazy-max** [comment]
@caspertone2003 Already in the doc :

![image](https://user-images.githubusercontent.com/1951866/58405969-e47f1a80-8068-11e9-9a4f-2a01e393a7d5.png)

:upside_down_face:

**Comment by caspertone2003** [comment]
@crazy-max 

So, it was there and I did not read it... very sorry

I am becoming TL;DR...

![image](https://user-images.githubusercontent.com/4682903/58439163-f4cbdf80-80d2-11e9-8ddb-6bd18e45e15c.png)

**Comment by caspertone2003** [comment]
@crazy-max 
Would it be possible to have a x32 version of docker-toolbox?
I cannot run x64 machines inside a virtual box guest, as VT-x cannot be chained ;-)

![image](https://user-images.githubusercontent.com/4682903/58489128-ed581500-816a-11e9-97a4-1b4e8e61a11e.png)

Thanks again!

**Comment by crazy-max** [comment]
@caspertone2003 https://github.com/portapps/docker-toolbox-portable/issues/4#issuecomment-468375365

**Comment by caspertone2003** [comment]
@crazy-max 

on another point, I got this when running in x64 host...
![image](https://user-images.githubusercontent.com/4682903/58492603-8722c080-8171-11e9-8ec2-1223e2dd2a89.png)

seems not to be using system defined proxy, but iso is there...., look:

![image](https://user-images.githubusercontent.com/4682903/58492757-d832b480-8171-11e9-9d9b-1de0beb28403.png)

**Comment by caspertone2003** [comment]
@crazy-max 
ok, i run second time, this time was better, but to no success....

![image](https://user-images.githubusercontent.com/4682903/58494756-1df17c00-8176-11e9-97c0-879ee8ad7ad9.png)

I have no administrative priviledge so I cannot install network adaptors...

Now I would ask you to include in doc that administrative priviledges are needed to  run successfully this portable.

CT
