### ISSUE TITLE
Why boot2docker.iso is included in the setup?

### ISSUE THREAD

**Issue by devsporadic** [portapps/docker-toolbox-portable#6]
Hi!

I wonder why boot2docker.iso is included in the setup. When docker-machine creates the vm, it downloads boot2docker.iso and does not use the iso from the setup. If boo2docker.iso was located in data\storage\cache, then docker-machine would use it and would not have to download it again.

Thanks a lot!

**Comment by crazy-max** [comment]
Hi @devsporadic, thanks for this suggestion, I will take a look on it.

**Comment by crazy-max** [comment]
#22
